info:
  name: Mentor Hub
  description: A platform to connect mentors with engineers engaged in a life long learning journey.
  slug: MentorHub
  developer_cli: mh
  mongodb_name: mentor_hub

organization:
  name: Agile Learning Institute
  founded: 2024
  slug: agile-learning-institute
  git_host: https://github.com
  git_org: agile-learning-institute
  docker_host: ghcr.io
  docker_org: agile-learning-institute

